### ISSUE TITLE
Feat: Decide on First Metric

### ISSUE THREAD

**Issue by jdhaines** [rropen/SFM#24]
- [ ] Determine your first metric
- [ ] Agree on math and plan for it (likely info from GitHub issues & PRs)
- [ ] Get the MVP for it working so the Frontend team can pull it in

**Comment by geiger96** [comment]
This issue seems complete. The only question is the "Agree on math and plan for it (likely info from GitHub issues & PRs)". We have a converter endpoint to take github payloads and convert them into database rows depending on event type, but we have yet to hook it up to a webhook to try it. I think until we get full webhooks setup the topics here are complete. Also we will need to query the GitHub API to get data that is already a part of the repos and won't be delivered in webhook payloads.

**Comment by jdhaines** [comment]
@geiger96 agreed! Great work!
